--IREPORT DE PROGRAMAS ACTIVIDADES
SELECT AN_INICIO_L, NOM_PROG, count(cod_act) as TOT_ACT FROM ACTIVIDAD_EN_PROGRAMA ACT
INNER JOIN PROGRAMA PRG ON PRG.COD_PROG = ACT.COD_PROG
INNER JOIN MATRICULACION MAT ON MAT.IDMATRICULA = PRG.IDMATRICULA
INNER JOIN ANO_LECT LEC ON LEC.ID_AN_LECTIVO = MAT.ID_AN_LECTIVO
where an_inicio_l = '2021-08-30' 
GROUP BY LEC.ID_AN_LECTIVO, PRG.COD_PROG